branch-defaults:
  master:
    environment: betz-env
    group_suffix: null
global:
  application_name: betz
  default_ec2_keyname: null
  default_platform: Ruby 2.1 (Puma)
  default_region: us-east-1
  profile: eb-cli
  sc: git
